# This file is sourced by bash at the close of every login shell.  For
# more info type `man bash'.

# If we have a custom file, source that as well
if [ -r ~/.bashrc_logout.custom ]; then
    source ~/.bashrc_logout.custom
else
      echo logging out...
fi

# --------------------------------------------------------------------
